### PR TITLE
fix: avoid removing the error log when initdb/createdb fails

### PR DESCRIPTION
**Pull request by haitlahcen**
This PR will allow the user to access to the error log when the `startAndLogToTmp` fail.

A temporary directory `tmp/tmp-postgres` is created by `startAndLogToTmp` where the error log is redirected. Because of the (previously used) `throwIO`, the error was handled by the `teardownDB` which was recursively removing the aforementioned temporary directory. The user had no way of checking what happened. 

This fix will avoid the removal and allow the user to check the error log.

### CODE REVIEW

**Comment by jfischoff** [comment]
I think this change is okay but I feel like the issue is that we should expose more of the options `tmp-postgres` has so users can choose their own log location. 

The code works by delaying the exception so it occurs in the creation call of the resource pool. Since the exception occurs in the setup function it should be thrown there IMO.

I'm specifically thinking the function [startWithHandles](https://hackage.haskell.org/package/tmp-postgres-0.1.1.1/docs/Database-Postgres-Temp.html#v:startWithHandles) should be exposed ... maybe like 
```haskell
setupDBWithHandles :: Handle -> Handle -> (Connection -> IO ()) -> IO TestDB
```

Thoughts?

**Comment by haitlahcen** [comment]
Your idea is better :)

**Comment by haitlahcen** [comment]
@jfischoff fixed

**Comment by tchoutri** [comment]
@haitlahcen Could you add an example use of `setupDBWithHandles` or add a test that uses it? :)

**Comment by hussein-aitlahcen** [comment]
@tchoutri Hi! This PR is suuuuuper old, let me pull everything back and check it out :).

**Comment by tchoutri** [comment]
@haitlahcen Wonderful. :)

**Pull request closed without merging**
